name: Check frontend code lint
on: 
  pull_request:
    paths:
      - 'web-app/client/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Set Node.js 16.x
          uses: actions/setup-node@v4
          with:
            node-version: 16.x
        
        - name: Install yarn
          run: npm install --global yarn
        
        - name: Install dependencies
          working-directory: web-app/client
          run: yarn install --check-files
        
        - name: Run lint
          working-directory: web-app/client
          run: yarn lint

